spring.application.name=identity-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/identity_db
spring.datasource.username=ecommerce
spring.datasource.password=ecommerce_local
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.public-key=classpath:keys/public.pem
jwt.private-key=classpath:keys/private.pem
jwt.expiration-ms=86400000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
