spring:
  application:
    name: notification-service
  datasource:
    url: ${NOTIF_DB_URL:jdbc:postgresql://localhost:5433/ecommerce_db}
    username: ${NOTIF_DB_USERNAME:ecommerce}
    password: ${NOTIF_DB_PASSWORD:ecommerce_local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:ecommerce}
    password: ${RABBITMQ_PASSWORD:ecommerce_local}
  mvc:
    problemdetails:
      enabled: true

server:
  port: ${SERVER_PORT:8087}

jwt:
  public-key: ${JWT_PUBLIC_KEY:classpath:keys/public.pem}
  issuer: ${JWT_ISSUER:mini-ecommerce}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
